from enum import Enum, IntFlag, auto

class AxisStatus(IntFlag):
    Homed = auto()
    Profiling = auto()
    WaitDone = auto()
    CommandValid = auto()
    Homing = auto()
    Enabling = auto()
    JogGenerating = auto()
    Jogging = auto()
    DrivePending = auto()
    DriveAbortPending = auto()
    TrajectoryFiltering = auto()
    IFOVEnabled = auto()
    NotVirtual = auto()
    CalEnabled1D = auto()
    CalEnabled2D = auto()
    MasterSlaveControl = auto()
    JoystickControl = auto()
    BacklashActive = auto()
    GainMappingEnabled = auto()
    Stability0 = auto()
    MotionBlocked = auto()
    MoveDone = auto()
    MotionClamped = auto()
    GantryAligned = auto()
    GantryRealigning = auto()
    Stability1 = auto()
    ThermoCompEnabled = auto()


class DriveStatus(IntFlag):
    Enabled = auto()
    CwEOTLimit = auto()
    CcwEOTLimit = auto()
    HomeLimit = auto()
    MarkerInput = auto()
    HallAInput = auto()
    HallBInput = auto()
    HallCInput = auto()
    SineEncoderError = auto()
    CosineEncoderError = auto()
    ESTOPInput = auto()
    BrakeOutput = auto()
    GalvoPowerCorrection = auto()
    NoMotorSupply = auto()
    CurrentClamp = auto()
    MarkerLatch = auto()
    PowerLimiting = auto()
    PSOHaltLatch = auto()
    HighResMode = auto()
    GalvoCalEnabled = auto()
    AutofocusActive = auto()
    ProgramFlash = auto()
    ProgramMXH = auto()
    ServoControl = auto()
    InPosition = auto()
    MoveActive = auto()
    AccelPhase = auto()
    DecelPhase = auto()
    EncoderClipping = auto()
    DualLoopActive = auto()
    InPosition2 = auto()


class AxisFault(IntFlag):
    PositionError = auto()
    OverCurrent = auto()
    CwEOTLimit = auto()
    CcwEOTLimit = auto()
    CwSoftLimit = auto()
    CcwSoftLimit = auto()
    AmplifierFault = auto()
    PositionFbk = auto()
    VelocityFbk = auto()
    HallFault = auto()
    MaxVelocity = auto()
    EstopFault = auto()
    VelocityError = auto()
    ProbeFault = auto()
    ExternalFault = auto()
    MotorTemp = auto()
    AmplifierTemp = auto()
    EncoderFault = auto()
    CommLost = auto()
    GantryMisalign = auto()
    FbkScalingFault = auto()
    MrkSearchFault = auto()
    SafeZoneFault = auto()
    InPosTimeout = auto()
    VoltageClamp = auto()
    PowerSupply = auto()
    MissedInterrupt = auto()
    Internal = auto()


class TaskStatus(Enum):
    Unavailable = auto()
    Inactive = auto()
    Idle = auto()
    ProgramReady = auto()
    ProgramRunning = auto()
    ProgramFeedheld = auto()
    ProgramPaused = auto()
    ProgramComplete = auto()
    Error = auto()
    Queue = auto()


class QueueStatus(Enum):
    QueueActive = auto()
    QueueEmpty = auto()
    QueueFull = auto()
    QueueStarted = auto()
    QueuePaused = auto()
    QueueLargeProgram = auto()
